# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Write Forward
email: green.matt@comcast.net
description: > # this means to ignore newlines until "baseurl:"
  The Write Forward Logging Framework for Java simplifies logging for Java.
  Write easy-to-use, portable, and future-proof logging code. Works with
  SLF4J, Log4J, Logback, and java.util.logging.
baseurl: "/Write-Forward" # the subpath of your site, e.g. /blog
url: "http://prichmp.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  prichmp
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "none"

# Build settings
markdown: kramdown
